"""allow nullable profile fields

Revision ID: 810f8b92a8b3
Revises: 71d2df5bec08
Create Date: 2026-08-25 16:52:49.504032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '810f8b92a8b3'
down_revision: Union[str, Sequence[str], None] = '71d2df5bec08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column(
    'users',
    'idade',
    existing_type=sa.VARCHAR(length=3),
    type_=sa.Integer(),
    nullable=True,
    postgresql_using='idade::integer'
)
    op.alter_column('users', 'peso',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('users', 'altura',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'sexo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'objetivo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'tipo_treino',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'horario_treino',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'horario_treino',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('users', 'tipo_treino',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'objetivo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'sexo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'altura',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('users', 'peso',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('users', 'idade',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('users', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
